### ISSUE TITLE
Jenkins env vars do not work with Pipeline Plugin

### ISSUE THREAD

**Issue by jonesetc** [percy/percy-client#12]
A relatively new way to build git projects is with the [Pipeline Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Pipeline+Plugin), which includes the [Multi-Branch Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Pipeline+Multibranch+Plugin). These set different environmental variables than the [GitHub PR Builder Plugin](https://wiki.jenkins-ci.org/display/JENKINS/GitHub+pull+request+builder+plugin), which Percy natively supports.

This causes problems like all builds being listed as detached heads instead of the actual branches, unless the [optional variables](https://percy.io/docs/learn/env-vars#optional) are set manually.

Here are the variables I see that expect the PR Builder Plugin, and what the Pipeline Plugin provides:
- [ghprbPullId -> CHANGE_ID](https://github.com/percy/percy-client/blob/c1750b37220b81644ed01bcbbceac60b14467a1d/lib/percy/client/environment.rb#L20)
- [ghprbTargetBranch -> BRANCH_NAME](https://github.com/percy/percy-client/blob/c1750b37220b81644ed01bcbbceac60b14467a1d/lib/percy/client/environment.rb#L103)
- [ghprbPullId -> CHANGE_ID](https://github.com/percy/percy-client/blob/c1750b37220b81644ed01bcbbceac60b14467a1d/lib/percy/client/environment.rb#L179)

**Comment by fotinakis** [comment]
Hey @jonesetc — thanks for this info, very helpful.

Before we update this and our other client libraries to natively support it, can you use our override variables to make sure things work in your Pipeline Plugin environment?

```bash
export PERCY_PULL_REQUEST="$CHANGE_ID"
export PERCY_BRANCH ="$BRANCH_NAME"
```

If the commit SHA is no longer stored in `GIT_COMMIT`, you'll also need to `export PERCY_COMMIT="$SOME_PIPELINE_ENV_VAR_FOR_COMMIT_SHA"`

If that works for you, we can update our libraries to check if Pipeline is used vs. GHPRB.

**Comment by jonesetc** [comment]
Thanks for the quick response.

Setting `PERCY_BRANCH` to `$BRANCH_NAME` works and is what we started doing to work around our issue of master builds not being recognized as such. I will do a little bit of testing to set those other two variables and make sure.

I'm guessing that if `PERCY_PULL_REQUEST` is set correctly, the UI for the build will have a link back to that PR?

**Comment by fotinakis** [comment]
Yup!

**Comment by jonesetc** [comment]
So, I did a little bit of testing, and here's the general information:

- `BRANCH_NAME` is a replacement for `ghprbTargetBranch`, and is always available
- `CHANGE_ID` is a replacement for `ghprbPullId`, but is not always available
    - The Pipeline Plugin can be configured to build all branches, not just PRs, and as such does not usually have this set on the env
- There is no available variable that serves the same information as `GIT_COMMIT`, so it would require the fallback to parsing raw `git` output
    - The Pipeline Plugin is built abstractly from all SCM systems, so specific things like commits are not available in the environment
    - The commit hash is available elsewhere to the user, but would still require the user to manually set it on the environment

I'd be happy to make a PR for this that would basically:
- Add a new `current_ci` tag called `:jenkins-pipeline`
- `_commit_sha` would still fall through and use the `_raw_commit_output('HEAD')`
- `branch` would use `ENV['BRANCH_NAME']`
- `pull_request_number` would use `ENV['CHANGE_ID']` if available

**Comment by fotinakis** [comment]
👍  Sounds good to us, @jonesetc! Thanks for doing that research as well.

**Comment by NahidSiddiqui** [comment]
I am using pipeline and was wondering how I can trigger off builds from multibranch pipeline project but some reason I cannot get the value for CHANGE_ID for a branch that has a pending pull request active. I use a Jenkins file that is stored in the repo and I was looking to trigger off builds using the code in the Jenkins file which needs to detect the pull request using CHANGE_ID. I tried using sh " echo env.CHANGE_ID" but this returns null. However I do get a value for sh "echo env.BRANCH_NAME".
