### ISSUE TITLE
invalid byte sequence in US-ASCII

### ISSUE THREAD

**Issue by joscha** [percy/percy-client#19]
In some odd CI builds I get:

```
An error occurred in a `before(:suite)` hook.
--
  | Failure/Error: build = Percy::Capybara.initialize_build
  |  
  | ArgumentError:
  | invalid byte sequence in US-ASCII
  | # ./vendor/bundle/ruby/2.4.0/gems/percy-client-1.11.0/lib/percy/client/environment.rb:39:in `match'
  | # ./vendor/bundle/ruby/2.4.0/gems/percy-client-1.11.0/lib/percy/client/environment.rb:39:in `match'
  | # ./vendor/bundle/ruby/2.4.0/gems/percy-client-1.11.0/lib/percy/client/environment.rb:39:in `block in commit'
  | # ./vendor/bundle/ruby/2.4.0/gems/percy-client-1.11.0/lib/percy/client/environment.rb:47:in `commit'
  | # ./vendor/bundle/ruby/2.4.0/gems/percy-client-1.11.0/lib/percy/client/builds.rb:7:in `create_build'
  | # ./vendor/bundle/ruby/2.4.0/gems/percy-capybara-2.5.1/lib/percy/capybara/client/builds.rb:19:in `block in initialize_build'
  | # ./vendor/bundle/ruby/2.4.0/gems/percy-capybara-2.5.1/lib/percy/capybara/client.rb:68:in `rescue_connection_failures'
  | # ./vendor/bundle/ruby/2.4.0/gems/percy-capybara-2.5.1/lib/percy/capybara/client/builds.rb:18:in `initialize_build'
  | # ./vendor/bundle/ruby/2.4.0/gems/percy-capybara-2.5.1/lib/percy/capybara.rb:29:in `initialize_build'
  | # ./spec/spec_helper.rb:36:in `block (2 levels) in <top (required)>'
  |  
  | An error occurred in an `after(:suite)` hook.
  | Failure/Error: $build_url = build['data']['attributes']['web-url']
  |  
  | NoMethodError:
  | undefined method `[]' for nil:NilClass
  | # ./spec/spec_helper.rb:40:in `block (2 levels) in <top (required)>'
```

Not sure, yet, when or why exactly this happens.

**Comment by timhaines** [comment]
Hi @joscha. Thanks for reporting this. I'd like to get it figured out with you and resolved ASAP.

It looks to me that the line in question is dealing with information about the [current commit](https://github.com/percy/percy-client/blob/master/lib/percy/client/environment.rb#L90).  Do you happen to have emoji or weird string values in the commit names or descriptions?  If you do, and could send those to me, I think that'll help me reproduce and resolve this.

If there's nothing obvious, could you try reproducing the [git show](https://github.com/percy/percy-client/blob/master/lib/percy/client/environment.rb#L92) command, and putting the output in a gist for us please?

**Comment by joscha** [comment]
> to have emoji or weird string values in the commit names or descriptions

yes, it actually rings a bell, I think there was a 🥒 and 🐒 in the PR title, haha - Unfortunately I can't find that build any more right now :(

**Comment by joscha** [comment]
Got it:

```shell
git show --quiet $SHA --format='COMMIT_SHA:%H%nAUTHOR_NAME:%an%nAUTHOR_EMAIL:%ae%nCOMMITTER_NAME:%an%nCOMMITTER_EMAIL:%ae%nCOMMITTED_DATE:%ai%nCOMMIT_MESSAGE:%B' 2> /dev/null
```

yields:
```
COMMIT_SHA:***
AUTHOR_NAME:Joscha Feth
AUTHOR_EMAIL:joscha@feth.com
COMMITTER_NAME:Joscha Feth
COMMITTER_EMAIL:j***@***.com
COMMITTED_DATE:2017-07-13 15:13:02 +1000
COMMIT_MESSAGE:[web]: <U+1F952> & <U+1F412> (#11691)
```

I censored a bit with `***`

**Comment by timhaines** [comment]
@joscha Thanks so much!  I'll be able to reproduce and fix it from what you've provided.

**Comment by timhaines** [comment]
@joscha I've spent some time looking at this today, and the only way I can reproduce it is by forcing my tests to run in an ASCII locale.  i.e. `LANG=en_US.US-ASCII bundle exec rake test`

Is the CI server where you were getting the errors setup to handle unicode correctly?  If you add `echo $LANG` before running your specs, what does it output?

**Comment by timhaines** [comment]
Or even better, run `locale` on your CI server.

**Comment by joscha** [comment]
We just had another failure

```
COMMIT_SHA:***
AUTHOR_NAME:*** Zyński
AUTHOR_EMAIL:***@users.noreply.github.com
COMMITTER_NAME:*** Zyński
COMMITTER_EMAIL:***@users.noreply.github.com
COMMITTED_DATE:2017-07-31 11:15:40 +1000
COMMIT_MESSAGE:Editor xyz *** (#12614)

Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor
```

seems the `ń` also breaks the percy client. I haven't gotten around to test what `locale` returns, will follow up later this week.

**Comment by joscha** [comment]
`locale` yields:

```
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

doesn't seem as if there is any `ASCII` in the `LANG` @timhaines

**Comment by timhaines** [comment]
@joscha Thanks for running that.  This is becoming a puzzle.

**Comment by joscha** [comment]
We're on `ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]` - maybe regular expressions in that ruby version on non-ASCII is not allowed, yet?

**Comment by timhaines** [comment]
@joscha hmm, it could be that.  It would be worth looking into and confirming.

[Support for ruby 1.9.3 ended over 2 years ago](https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/), but I'm sure your team knows that. :)

Support for ruby 2.1 ended [earlier this year](https://www.ruby-lang.org/en/news/2017/04/01/support-of-ruby-2-1-has-ended/) too.

**Comment by timhaines** [comment]
Poking around with this locally on a newer Ruby 1.9.3, I've got a commit with the same unicode characters you were using earlier, and don't get an error with the regex (from irb).  They do print differently in irb though, like this: `COMMIT_MESSAGE:\u{1F952} and 🐒`

**Comment by joscha** [comment]
hmm, I have nothing then :( I just know it fails on commits with "weird" characters. If it was only the title, I think it wouldn't be a problem, but given that we have someone with `ń` in their name, this might become a problem...

**Comment by timhaines** [comment]
Yeah, I agree.  I'd like to get to the bottom of this @josha.  I'll spend some more time thinking on it.  Do you think you could put together a really simple 1-3 line ruby script that just tries matching the regex against a unicode string, and see if you can reproduce the error?

**Comment by joscha** [comment]
I can; just double checked, we run Percy via rbenv actually, and that is a ruby `2.4.1`

**Comment by joscha** [comment]
Seeing the same one now with the name `Andrés`

**Comment by joscha** [comment]
@timhaines I found this: https://stackoverflow.com/a/17031719 - maybe we can give that a try?

**Comment by fotinakis** [comment]
I think that's only going to help if there are unicode characters in the Ruby source directly, not if they're being parsed from command-line output.

**Comment by joscha** [comment]
that would make sense - do you think it could have something to do with the locale at the time we build ruby using rbenv and ruby-build?

**Comment by fotinakis** [comment]
I guess it could? I'm not exactly sure how that stuff works but you might try setting `LANG=en_US.UTF-8` or `LANGUAGE="en_US.UTF-8"` (https://stackoverflow.com/a/12650490/128597) at build time.

Is the repo you're hitting this on open source? We could try to replicate it locally at specific commits that have authors like `Andrés`

**Comment by joscha** [comment]
I am currently trying
```
export LC_ALL=C.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
```
as suggested in https://github.com/ffaker/ffaker/issues/277#issuecomment-263519146
via
`git commit -m'try to fix ASCII error' --author="Jóschá Féth <joscha@***.com>"` 🤣

**Comment by timhaines** [comment]
@joscha Did that solve it for you?

**Comment by timhaines** [comment]
If this doesn't solve it, perhaps we can try reproducing it in a simple docker image with a sample app and troubleshoot it from there.

**Comment by joscha** [comment]
It does solve it, opened https://github.com/percy/percy-docs/pull/37

**Comment by timhaines** [comment]
@joscha Thanks for the follow up here, and for the docs PR.  I'd love to understand why that was required.  Perhaps because your `LANGUAGE` var wasn't set previously.  Or the `LC_ALL` var - but that seems to serve a more global purpose.  Do you have something intentionally unsetting those in your environment?

If you're using a docker container with a public base image/Dockerfile, I'd be interested to spend a little time looking at this to learn more.

**Comment by joscha** [comment]
> Do you have something intentionally unsetting those in your environment?

Nope, not that I know of.

> If you're using a docker container with a public base image/Dockerfile, I'd be interested to spend a little time looking at this to learn more.

It's a normal EC2 machine with an Ubuntu Trusty-based image - ruby is the version named above coming via rbenv. Haven't investigated which of the three vars makes the difference, should be easy to test in a Unit test however.

**Comment by timhaines** [comment]
From the adhoc blog posts I've been reading, it looks like EC2's Ubuntu images don't have a default `LANGUAGE` or `LC_ALL` set.  I wish I had a better source, but there's [this](https://kimambo.de/fixing-locale-setting-on-ubuntu-14-04-ec2-instances/), [this](https://ders.github.io/post/2014-01-10-aws-locale/), and [this](http://www.pixelninja.me/how-to-fix-invalid-locale-setting-in-ubuntu-14-04-in-the-cloud/).

It's a little surprising this hasn't surfaced in other ways for you.

**Comment by joscha** [comment]
> It's a little surprising this hasn't surfaced in other ways for you.

I had to add Ruby to our images for percy only :)

**Comment by fotinakis** [comment]
Now that we understand the issue I was able to reproduce it locally by doing `unset LANG` and then adding a commit author with special characters. Was able to fix this directly in percy-client: https://github.com/percy/percy-client/pull/22

**Comment by fotinakis** [comment]
Fix released in percy-client v1.13.3 — thanks for all the debugging work here!

**Comment by timhaines** [comment]
@joscha I had no idea Canva wasn't using Ruby until Percy! Thanks for jumping through the hoops here, and persisting in tracking this down.  We appreciate the time you invested, and are super happy it's resolved.

**Comment by joscha** [comment]
Thanks for fixing it!
