### ISSUE TITLE
Consider providing a way to specify the baseline SHA for a Percy build

### ISSUE THREAD

**Issue by rsimha** [percy/percy-client#27]
This is a feature request stemming from the discussion in https://github.com/ampproject/amphtml/issues/11385, and from 1:1 conversations with @fotinakis.

The `ampproject/amphtml` project uses forked repos for development, due to which github's API has no way of knowing a PR's branch point off of the mainline `master` branch. This is messing with Percy's automatic baseline picking logic, and is proving to be problematic in a bunch of ways.

If we have a way to provide Percy with a branch point SHA which can be used during baseline picking, we'd be able to mitigate all related problems.

/to @fotinakis @timhaines

**Comment by timhaines** [comment]
This is now provided with `PERCY_TARGET_COMMIT`. Closing this issue.

**Comment by rsimha** [comment]
Thanks for the update!

/cc @danielrozenberg

**Comment by danielrozenberg** [comment]
Just to make sure, this is also available if I use the percy-puppeteer v0.4.0 dependency, correct?

**Comment by timhaines** [comment]
@danielrozenberg Yes.  percy-puppeteer v0.4.0 [includes a dependency](https://github.com/percy/percy-puppeteer/blob/master/package.json#L37) on percy-client v3.0.0.  PERCY_TARGET_COMMIT support was added in [percy-client v2.9.0](https://github.com/percy/percy-js/releases/tag/v2.9.0)

Mike emailed you both on July 20th about this btw, and @rsimha replied.  I can understand that it may not have been top priority at the time.  :)

Also - we've updated our back-end to automatically look at the merge-base between the two branches now (via pinging GitHub's compare end-point) and then finding the associated Percy build if it exists.. So if that's what your own code is doing, then you may just be able to remove it?  I vaguely remember you're modifying branch names in what you send to Percy though - and if that's the case, our automatic system may not work..

**Comment by danielrozenberg** [comment]
I'm cc'ing you on our PR and continuing this conversation there (since I believe it's not that relevant to the current thread)
