### ISSUE TITLE
Percy <-> Github integration is not picking up the latest Percy build for a PR, thereby blocking it from being merged

### ISSUE THREAD

**Issue by rsimha-amp** [percy/percy-client#30]
I have a PR at https://github.com/ampproject/amphtml/pull/11827, for which Travis CI ran Percy visual diff tests that passed. However, Percy <-> github integration is showing a red cross mark against the PR that links to an older failed build even though the latest Travis test run's Percy build happened after the failed build.

Screenshot from PR:
![image](https://user-images.githubusercontent.com/26553114/32810444-eae30458-c968-11e7-8f26-fd8dbee7347a.png)

This links to Percy build [# 6421](https://percy.io/ampproject/amphtml/builds/407386)

However, the latest [Travis build](https://travis-ci.org/ampproject/amphtml/jobs/302056381) from the PR generated Percy build [# 6423](https://percy.io/ampproject/amphtml/builds/407409), which was successful.

We enforce Percy checks in our repository, so this issue is blocking some of our PRs from being merged. 

@timhaines @fotinakis is this a known problem? Or could I be missing something?

**Comment by rsimha-amp** [comment]
Screenshot of Percy builds. I expect to see the newer build linked to my PR.

![image](https://user-images.githubusercontent.com/26553114/32810560-841c2118-c969-11e7-8490-6837ece3640b.png)

**Comment by rsimha-amp** [comment]
Update: I was forced to run a full Travis CI build in order to get past the percy block. I'm leaving this issue open in case you'd like to take a look through the logs at your end.

**Comment by timhaines** [comment]
@rsimha-amp Thanks for mentioning this and supplying details Raghu!  I know why this happens - super infrequently, but has a bad impact when it does.  

The underlying cause is that we sometimes get a failed response (50x/timeout) from GitHub's API when we try and set the commit status, and don't have retries in place yet.  I've added a story to our next sprint to get retries in place.

**Comment by rsimha-amp** [comment]
Glad you have this on your radar. Thanks for the update!

**Comment by fotinakis** [comment]
@rsimha-amp we have an idea of where this may have come from and are looking more deeply into it. In the meantime, we actually recommend that you uncheck having Percy a "required" commit status check in your protected branch GitHub settings, so that it doesn't cause you to be blocked on merge.

**Comment by fotinakis** [comment]
@rsimha-amp oops sorry missed @timhaines's reply, that's exactly right. As mentioned, you can also disable the required status check to make things slightly more flexible for that failure mode in the meantime.
