### ISSUE TITLE
Percy::Config option for ignoring build resources?

### ISSUE THREAD

**Issue by christophemaximin** [percy/percy-client#4]
What would you suggest is the best option name?
What about this?  https://gist.github.com/christophemaximin/81f7c2d8f4bc5263a626c3f713925b8a

**Comment by fotinakis** [comment]
So let's see, in this case it will be used exclusively to ignore build resources, right? So maybe `ignored_resources` or `ignored_resource_paths`? With a comment that says these can be paths or regexes.

**Comment by fotinakis** [comment]
Probably `ignored_resource_paths`

**Comment by christophemaximin** [comment]
Sounds good;
Just to be sure, we agree that this option won't actually be used by `percy-client`, but only in `percy-capybara`  (for now) when I make another PR for using this option there?

**Comment by fotinakis** [comment]
Yup — could you just include that fact in the comment over the option? Or, we could do something more correctly abstract like add a `ignore_build_resource?(path)` public method to percy-client and then use that method in percy-capybara since we hold a client object there.

**Comment by christophemaximin** [comment]
Where would you suggest `ignore_build_resource?(path)` be defined? As a instance method of Percy::Client or elsewhere?

**Comment by christophemaximin** [comment]
How about a simpler way?
- Having a `ignore_build_resource` config option, with a default value of `lambda { |path| false }`
- End-users can redefine this config option as they see fit
- In percy-capybara we call this config option to check whether to ignore the resource or not
